config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "events#top"
  resources :users, only: [:edit, :update]
  resources :events, only: [:index, :new, :create, :edit,
  :update, :destroy] do
    get 'edit_template'
    get 'new_template', on: :collection
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  TEMPLATES = {
    bath_cleaning: '風呂掃除',
    checking_post: '郵便の確認',
    cooking_papa: '朝ごはんをつくる',
    garvage_removal: 'ゴミ出し',
    ready_to_go_to_kindergarten: '保育園の準備',
    toilet_cleaning: 'トイレ掃除',
    walking_dog: '犬の散歩',
    washing_clothes: '洗濯'
  }.freeze
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configue_permitted_parameters, if: :devise_controller?

  private

  def configue_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def top; end

  def index
    @events = Event.all
    render json: @events.map { |event|
      {
        id: event.id,
        title: event.title,
        start: event.start_at,
        color: event.is_done ? '#AAAAAA' : nil
      }
    }
  end

  def new
    @event = Event.new
    @event.title = '新規イベント'
    @event.title = Event::TEMPLATES[params[:template_key].to_sym] if params[:template_key]
    @event.start_at = params[:date]
  end

  def create
    @event = Event.new(event_params)
    if params[:template_key]
      @event.image.attach(
        io: File.open(Rails.root.join('public', "#{params[:template_key]}.png")),
        filename: "#{params[:template_key]}.png",
        content_type: 'image/png'
      )
    end
    @event.save
    redirect_to root_path
  end

  def edit
    @event = Event.find(params[:id])
    @event.title = Event::TEMPLATES[params[:template_key].to_sym] if params[:template_key]
  end

  def update
    @event = Event.find(params[:id])
    if params[:template_key]
      @event.image.attach(
        io: File.open(Rails.root.join('public', "#{params[:template_key]}.png")),
        filename: "#{params[:template_key]}.png",
        content_type: 'image/png'
      )
    end
    @event.update(event_params)
    redirect_to root_path
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path
  end

  def edit_template
    @event = Event.find(params[:event_id])
  end

  private
  def event_params
    params.require(:event).permit(:title, :start_at, :image, :is_done)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit; end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/create.js.erb
$('#calendar').fullCalendar(
  'renderEvent',
  $.parseJSON("<%=j render(@event, format: :json).html_safe %>"),
  true
);
$('.modal').modal('hide');

app/views/events/edit.html.erb
<div class="container mt-3">
<div class="low">
<%= form_with model: @event, local: true do |f| %>
  <div class="mb-3">
    <label class="form-label">Titlte</label>
  <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <label class="form-label">Datetime</label>
    <%= f.datetime_local_field :start_at, class: 'form-control'%>
  </div>

    <div class="mb-3">
    <label class="form-label">isDone</label>
    <%= f.check_box :is_done, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <label class="form-label">Image</label>
    <%= f.file_field :image, id:"img" %>
  <img id="preview" width="200">
  </div>
      <% if params[:template_key] %>
        <%= hidden_field_tag :template_key, params[:template_key] %>
        <%= image_tag "/#{params[:template_key]}.png", class: 'message-image' %>
      <% elsif @event.image.attached? %>
        <%= image_tag @event.image.variant(resize: '500x500'), class: 'message-image' %>
      <% end %>
<div class="buttons d-flex justify-content-between">
  <div class="left_buttons d-flex mt-3">
  <button type="submit" class="btn btn-primary mr-3">登録</button>
  <%= button_to "削除", @event, method: :delete, class: "btn btn-danger mr-3", data: {confirm: "削除します。よろしいですか？"} %>

<%= link_to 'テンプレートから選択', event_edit_template_path(@event) ,class: "btn btn-secondary mr-3 pt-3 pb-3"%>
  </div>
<div class="right_button">
<%= link_to 'カレンダーへ戻る',root_path ,class: "btn btn-info mr-3 mt-3 pt-3 pb-3"%>
</div>
</div>
<% end %>
</div>

app/views/events/edit_template.erb
<div class="container mt-3">
<div class="row">
<% Event::TEMPLATES.each do |key, label| %>
<div class="col-4">
<%= link_to edit_event_path(@event, template_key: key) do %>
<div class="card" style="width: 18rem;">
  <%= image_tag "/#{key}.png", class: "card-img-top", alt: '...' %>
  <div class="card-body">
    <p class="card-text"><%= label %></p>
  </div>
</div>
<% end %>
</div>
<% end %>
</div>

app/views/events/index.html.erb
<div id="calendar"></div>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal1">
  Launch demo modal
</button>
<div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="label1" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="label1">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

     <div class="modal-body">
        <div class="form-group field">
          <%= form_with(model: @event, remote: true) do |f| %>
            <div class="form-inputs">
              <div class="form-group">
                <%= f.label :title, "予定", class: "form-control-label"%>
                <div class="input-group" data-target-input="nearest">
                  <%= f.text_field :title, class: "form-control"%>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :start, "開始時間", class: "form-control-label"%>
                <div class="input-group" data-target-input="nearest">
                  <%= f.text_field :start, class: "form-control"%>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :end, "終了時間", class: "form-control-label"%>
                <div class="input-group" data-target-input="nearest">
                  <%= f.text_field :end, class: "form-control"%>
                </div>
              </div>
            </div>

            <div class="modal-footer actions">
              <%= f.submit "入力完了", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">OK</button>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<%= javascript_pack_tag 'preview' %>
<div class="container mt-3">
<div class="low">
<%= form_with model: @event, local: true do |f| %>
  <div class="mb-3">
    <label class="form-label">Titlte</label>
  <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <label class="form-label">Datetime</label>
    <%= f.datetime_local_field :start_at, class: 'form-control'%>
  </div>

    <div class="mb-3">
    <label class="form-label">isDone</label>
    <%= f.check_box :is_done, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <label class="form-label">Image</label>
   <%= f.file_field :image, id:"img" %>
  <img id="preview" width="200">
​
  </div>
​
      <% if params[:template_key] %>
        <%= hidden_field_tag :template_key, params[:template_key] %>
        <%= image_tag "/#{params[:template_key]}.png", class: 'message-image' %>
      <% elsif @event.image.attached? %>
        <%= image_tag @event.image.variant(resize: '500x500'), class: 'message-image' %>
      <% end %>
 <div class="buttons d-flex justify-content-between">
  <div class="left_buttons d-flex mt-3">
  <button type="submit" class="btn btn-primary mr-3">Submit</button>
<%= link_to 'テンプレートから選択', new_template_events_path(date: params[:date]) ,class: "btn btn-secondary mr-3 pt-3 pb-3"%>
  <div id="image-list"></div>
​
  </div>
<div class="right_button">
<%= link_to 'カレンダーへ戻る',root_path ,class: "btn btn-info mr-3 mt-3 pt-3 pb-3"%>
</div>
</div>
​
  </div>
​
<% end %>
</div>
</div>

app/views/events/new_template.erb
<div class="container mt-3">
<div class="row">
<% Event::TEMPLATES.each do |key, label| %>
<div class="col-4">
<%= link_to new_event_path(template_key: key, date: params[:date]) do %>
<div class="card" style="width: 18rem;">
  <%= image_tag "/#{key}.png", class: "card-img-top", alt: '...' %>
  <div class="card-body">
    <p class="card-text"><%= label %></p>
  </div>
</div>
<% end %>
</div>
<% end %>
</div>
</div>

app/views/events/top.html.erb
<div id="calendar"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCalendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all' %>
<%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト",destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "カレンダーに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>